import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar/NavBar";
import StoreProvider from "../lib/StoreProvider";
import ToastContainerWrapper from "@/toastify/Toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
          <ToastContainerWrapper />
        </body>
      </html>
    </StoreProvider>
  );
}
